Contrast 34045 ssrf
Contrast-Security-OSS/HapiTestBench pull request #4
Opened 2019-06-10 22:32 UTC by cixel

2019-06-12 18:29 UTC, meandthemoon requested changes
Can you make sure that `$` loads before the view. The script in the HTML is throwing an exception and the page does not work.

2019-06-13 18:04 UTC, Avuxo approved these changes

2019-06-18 14:43 UTC, meandthemoon commented
Can you add the following to the top of `views/partials/header.ejs`:

```
<div id="javascripts">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</div>
```

2019-06-18 17:58 UTC, meandthemoon approved these changes

2019-06-18 19:23 UTC, merged