unsafe-file-upload
Contrast-Security-OSS/HapiTestBench pull request #8
Opened 2019-06-13 17:37 UTC by Avuxo

2019-06-17 17:42 UTC, cixel requested changes

2019-06-17 17:42 UTC, cixel commented on routes/unsafe-file-upload/index.js
> +          const filePath = path.join(__dirname, '../../uploads', name);
this should just be a path.resolve (each `'..'` as a separate arg) so that the file path doesn't look like `/app/a/b/../../uploads/blah`

2019-06-18 15:50 UTC, cixel approved these changes

2019-06-18 18:28 UTC, bizob2828 commented
I understand this is one way to handle multipart form but just seems like it's overkill.  we spoke in slack and they have an easy button that handles all the uploading for you.

See diff:
```
diff --git a/routes/unsafe-file-upload/index.js b/routes/unsafe-file-upload/index.js
index cbbb08f..3dc0481 100644
--- a/routes/unsafe-file-upload/index.js
+++ b/routes/unsafe-file-upload/index.js
@@ -19,39 +19,14 @@ exports.register = function unsafeFileUpload(server, options) {
       path: '/submit',
       options: {
         payload: {
-          output: 'stream',
+          output: 'file',
           parse: true,
           allow: 'multipart/form-data'
         }
       },
       handler: (request, h) => {
         const payload = request.payload;
-
-        if (payload.file) {
-          const name = payload.file.hapi.filename;
-          const filePath = path.resolve(path.join(
-            __dirname,
-            '..',
-            '..',
-            'uploads',
-            name
-          ));
-          const file = fs.createWriteStream(filePath);
-
-          file.on('error', (err) => console.error(err));
-
-          payload.file.pipe(file);
-
-          payload.file.on('end', (err) => {
-            const ret = {
-              filename: payload.file.hapi.filename,
-              headers: payload.file.hapi.headers
-            };
-            return JSON.stringify(ret);
-          });
-        }
-
-        return h.response('OK');
+        return { filename: payload.file.filename, headers: payload.file.headers };
     }},
   ]);
```

2019-06-20 15:09 UTC, merged